### ISSUE TITLE
downsampling during training 

### ISSUE THREAD

**Issue by Madhavan0123** [yoyololicon/diffwave-sr#3]
Hi 
thanks for the code base. Can you tell me where does the data get downsampled -upsampled during training in the code base? I am not able to find those lines in the code base

**Comment by yoyololicon** [comment]
Hi, 
we don't perform such operations during training because our target is to train an unconditional generative model as a prior. The upsampling happens at test time, where we proposed an algorithm to condition the sampling process with low resolution audio.

I hope this answers your question.
