### ISSUE TITLE
NU-Wave2 reproduction

### ISSUE THREAD

**Issue by yxlu-0102** [yoyololicon/diffwave-sr#4]
Hello, may I ask how many steps you have trained NU-Wave2 for? I couldn't achieve the metrics mentioned in the paper using their official checkpoint. If it's convenient for you, could you provide the checkpoint for your trained nuwave2?

**Comment by yoyololicon** [comment]
@yxlu-0102 Thanks for asking.
You can download the checkpoints from here:
https://drive.google.com/drive/folders/1guK563LP-h9NWd7ohLWP2_wAg_KUmeZD?usp=sharing
Unfortunately, I forgot which one I used in my paper 😅 
I picked the one that perform the best.
It's probably the `epoch=71` or `epoch=72` one, but definitely not `epoch=73`. 

I have to admit that their model performance fluctuates a lot during training. It's better to consistently monitor the process and pick the best one on the fly.

**Comment by yxlu-0102** [comment]
It did work! Thanks a million! 😭
